version: '3'

services:
  app:
    container_name: watcher
    build: .
    volumes:
      - .:/app
      - ../nginx-rtmp/videos:/tmp/videos
    environment:
      MEDIACMS_USER: "${MEDIACMS_USER}"
      MEDIACMS_PASSWORD: "${MEDIACMS_PASSWORD}"
      MEDIACMS_URL: "${MEDIACMS_URL}"